packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.2'
  - '@tanstack/react-query@5.102.2'

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  lightningcss: 1.29.1

patchedDependencies:
  react-native-css@3.0.7: patches/react-native-css@3.0.7.patch
